import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Keel Academy collects, uses, and protects your information.",
};

export default function PrivacyPage() {
  return (
    <div className="shell section">
      <header className="max-w-[68ch]">
        <p className="eyebrow">Legal</p>
        <h1 className="heading-xl mt-4">Privacy Policy</h1>
        <p className="lead mt-4">
          We respect your privacy. Here is the exact data we collect, why we need
          it, and how we handle it.
        </p>
      </header>

      <div className="mt-12 max-w-[68ch] space-y-10 text-[15.5px] leading-relaxed text-[color:var(--text-muted-on-dark)]">
        <section className="space-y-3">
          <h2 className="heading-md text-phosphor-white">1. Information we collect</h2>
          <p>
            When you sign in, we collect your email address and your name.
            If you sign in through Google or GitHub, we receive your basic profile info.
          </p>
          <p>
            When you submit coursework, we store your repository URL and commit hashes.
            We also store grading verdicts and test outputs generated by our runners.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-md text-phosphor-white">2. Payments and billing details</h2>
          <p>
            Paddle acts as our Merchant of Record. Paddle processes all payments
            and stores your billing details.
          </p>
          <p>
            We never see or store your full card number on our servers.
            Paddle shares your transaction ID, customer ID, and subscription status with us.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-md text-phosphor-white">3. How we use your information</h2>
          <p>
            We use your data to run your account and grade your assignments.
            We also use it to track your progress and send system updates.
          </p>
          <p>
            We do not sell your personal data to advertisers or third parties.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-md text-phosphor-white">4. Third-party services</h2>
          <p>
            We work with trusted partners to operate our platform.
            These partners include cloud hosting providers, authentication providers, and Paddle for payments.
            Each provider only accesses the data necessary to perform their service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-md text-phosphor-white">5. Your rights and data deletion</h2>
          <p>
            You can request a copy of your personal data at any time.
            You can also ask us to delete your account and associated records.
            To make a request, send an email to{" "}
            <a
              href="mailto:support@keelacademy.com"
              className="text-lime-pulse underline underline-offset-4"
            >
              support@keelacademy.com
            </a>
            .
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-md text-phosphor-white">6. Changes to this policy</h2>
          <p>
            We may update this policy as we release new platform features.
            We will post changes directly on this page with an updated revision date.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-md text-phosphor-white">7. Contact us</h2>
          <p>
            Have questions about how we handle your data? Reach out to us at{" "}
            <a
              href="mailto:support@keelacademy.com"
              className="text-lime-pulse underline underline-offset-4"
            >
              support@keelacademy.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
